support for postgresql 16
reorg/pg_repack pull request #345
Opened 2023-04-03 16:22 UTC by Melkij

Hello

So far there are no incompatible changes, 1.4.8 works with postgresql 16dev without any changes.

However, I propose to prepare a new release 1.4.9 as usual, I will mention postgresql 16 support in the change notes to eliminate any ambiguity.

Question for discussion: it is necessary to change the list of supported old versions? ( #338 )

PS: at the same time I want to check if pg16 is already available for our tests

2023-04-03 16:33 UTC, Melkij commented
>  update-alternatives: error: alternative path /usr/share/postgresql/16/man/man1/postmaster.1.gz doesn't exist
> dpkg: error processing package postgresql-16 (--configure):
>  installed postgresql-16 package post-installation script subprocess returned error exit status 2

The package is available, but its installation fails. I'll trigger the check few weeks later.

2023-04-20 10:15 UTC, andreasscherbaum commented
This is currently failing with an unrelated error in the package:

```

2023-04-20 10:17 UTC, andreasscherbaum commented on META.json
> +   "version": "1.4.9",
I would like to separate the update of support for PG 16 and the cut of a new release. These two do not necessarily have to go into a single PR.

2023-06-14 11:53 UTC, Melkij commented
I removed unrelated changes and ran tests locally. For postgresql 16 we didn't need any additional changes. This time, the github tests also passed without surprises.

2023-09-25 11:28 UTC, franciscoreinolds commented
Greetings!

Any news in regards to this? 👀

2023-09-25 12:07 UTC, Melkij commented
@franciscoreinolds , pg_repack 1.4.8 works fine with postgresql 16. No code changes were required. Regarding the mention of pg16 support in the documentation and tests... I lost the track.

@andreasscherbaum , I remember that a new release was planned.

2023-09-25 12:14 UTC, franciscoreinolds commented
Indeed, I meant more if there had been a discussion to release a new version with the content of this PR just to explicitly support PG 16 👌🏽

2023-09-25 17:36 UTC, andreasscherbaum commented
Yes, there is a bugfix we want to get in, and then release a version which mentions 16.

2023-10-20 14:57 UTC, dvarrazzo requested changes

2023-10-20 14:57 UTC, dvarrazzo commented on .github/workflows/regression.yml
> +          - 16
The file `doc/pg_repack.rst` must be updated too to declare the next version pg16-compatible.

2023-11-26 23:30 UTC, za-arthur commented
This was done by https://github.com/reorg/pg_repack/pull/364 and https://github.com/reorg/pg_repack/pull/372

2023-11-26 23:30 UTC, closed without merging